server:
  port: 9006
spring:
  application:
    name: yuehu_spit    #指定服务名
  data:
    mongodb:
      host: localhost
      database: spildb
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka