spring:
  application:
    name: yuehu-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/baichendongyang/yuehu_config.git
  rabbitmq:
    host: 127.0.0.1
server:
  port: 12000

management: #暴露触发消息总线的地址,用于URL中的后缀
  endpoints:
    web:
      exposure:
        include: bus-refresh