spring:
  application:
    name: yuehu-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/baichendongyang/yuehu_config.git
server:
  port: 12000
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka/
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus‐refresh