server:
  port: 9012
spring:
  application:
    name: yuehu‐weh #指定服务名
eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
zuul:
  routes:
    yuehu‐gathering: #活动
      path: /gathering/** #配置请求URL的请求规则
      serviceId: yuehu‐gathering #指定Eureka注册中心中的服务id
    yuehu‐article: #文章
      path: /article/** #配置请求URL的请求规则
      serviceId: yuehu‐article #指定Eureka注册中心中的服务id
    yuehu‐base: #基础
      path: /base/** #配置请求URL的请求规则
      serviceId: yuehu‐base #指定Eureka注册中心中的服务id
    yuehu‐friend: #交友
      path: /friend/** #配置请求URL的请求规则
      serviceId: yuehu‐friend #指定Eureka注册中心中的服务id
    yuehu‐qa: #问答
      path: /qa/** #配置请求URL的请求规则
      serviceId: yuehu‐qa #指定Eureka注册中心中的服务id
    yuehu‐recruit: #招聘
      path: /recruit/** #配置请求URL的请求规则
      serviceId: yuehu‐recruit #指定Eureka注册中心中的服务id
    yuehu‐spit: #吐槽
      path: /spit/** #配置请求URL的请求规则
      serviceId: yuehu‐spit #指定Eureka注册中心中的服务id
    yuehu‐user: #用户
      path: /user/** #配置请求URL的请求规则
      serviceId: yuehu‐user #指定Eureka注册中心中的服务id