server:
  port: 9008
spring:
  application:
    name: yuehu-user    #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/tensquare_user?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
  redis:
    host: 127.0.0.1
  rabbitmq:
    host: 127.0.0.1
jwt:
  config:
    key: baichen
    ttl: 3600000

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka

