server:
  port: 9004
spring:
  application:
    name: yuehu_qa    #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver    # 不能写成driver.class.name
    url: jdbc:mysql://127.0.0.1:3307/tensquare_article?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
  redis:
    host: 127.0.0.1
  data:
    mongodb:
      host: localhost
      database: recruitdb
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka