server:
  port: 9005
spring:
  application:
    name: yuehu_gathering    #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver    # 不能写成driver.class.name
    url: jdbc:mysql://127.0.0.1:3307/tensquare_gathering?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
  redis:
    host: 127.0.0.1