server:
  port: 9002
spring:
  application:
    name: yuehu-recruit   #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver    # 不能写成driver.class.name
    url: jdbc:mysql://127.0.0.1:3307/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka